#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
import textwrap


ROOT = Path(__file__).resolve().parents[1]


MODE_SPECS = {
    "bef830": {
        "trace": None,
        "func_off": 0xBEF830,
        "args": {"rdi": 0, "rsi": 1, "r9": 5},
        "scalars": {"rdx": "rdx", "rcx": "rcx", "r8": "r8"},
        "mutate": {"kind": "region", "blob": "rdi", "offset": 0x200, "capacity": 0x100},
    },
    "7f9060": {
        "trace": None,
        "func_off": 0x7F9060,
        "args": {"rdi": 0, "rsi": 1},
        "scalars": {"rdx": "rdx", "r8": "r8", "r9": "r9"},
        "mutate": {
            "kind": "len_region",
            "blob": "rsi",
            "offset": 0x100,
            "capacity": 0x180,
            "len_field1": 0x10,
            "len_field2": 0x18,
        },
    },
    "54ace0": {
        "trace": None,
        "func_off": 0x54ACE0,
        "args": {"rdi": 0, "rsi": 1},
        "scalars": {"rdx": "rdx"},
        "mutate": {"kind": "region", "blob": "rsi", "offset": 0x20, "capacity": 0x20},
    },
}


def c_bytes(blob: bytes) -> str:
    items = ", ".join(f"0x{b:02x}" for b in blob)
    return textwrap.fill(items, width=100, subsequent_indent="    ")


def sanitize_name(s: str) -> str:
    return s.replace("-", "_")


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--bef830-trace", required=True)
    ap.add_argument("--7f9060-trace", dest="trace_7f9060", required=True)
    ap.add_argument("--54ace0-trace", required=True)
    ap.add_argument(
        "--out",
        default=str(ROOT / "preload" / "cm_afl_native_assets.h"),
    )
    return ap.parse_args()


def load_trace(path: Path) -> dict:
    with path.open("r", encoding="ascii") as fp:
        return json.load(fp)


def parse_u64(s: str) -> int:
    if s.startswith("0x-"):
        return (-int(s[3:], 16)) & ((1 << 64) - 1)
    return int(s, 16) & ((1 << 64) - 1)


def main() -> int:
    args = parse_args()
    MODE_SPECS["bef830"]["trace"] = Path(args.bef830_trace)
    MODE_SPECS["7f9060"]["trace"] = Path(args.trace_7f9060)
    MODE_SPECS["54ace0"]["trace"] = Path(args.__dict__["54ace0_trace"])

    out = Path(args.out)
    lines: list[str] = []
    lines.append("/* generated by scripts/build_cm_afl_native_assets.py */")
    lines.append("#ifndef CM_AFL_NATIVE_ASSETS_H")
    lines.append("#define CM_AFL_NATIVE_ASSETS_H")
    lines.append("")
    lines.append("#include <stddef.h>")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("enum cm_native_mutate_kind {")
    lines.append("    CM_MUTATE_REGION = 1,")
    lines.append("    CM_MUTATE_RCX_PAYLOAD = 2,")
    lines.append("    CM_MUTATE_TWO_STRINGS = 3,")
    lines.append("};")
    lines.append("")
    lines.append("struct cm_native_blob_asset {")
    lines.append("    const char *label;")
    lines.append("    int arg_index;")
    lines.append("    uint64_t orig_addr;")
    lines.append("    size_t size;")
    lines.append("    const unsigned char *data;")
    lines.append("};")
    lines.append("")
    lines.append("struct cm_native_mode_asset {")
    lines.append("    const char *mode;")
    lines.append("    uint64_t orig_base;")
    lines.append("    uint64_t func_off;")
    lines.append("    uint64_t regs[6];")
    lines.append("    enum cm_native_mutate_kind mutate_kind;")
    lines.append("    int mutate_blob_index;")
    lines.append("    size_t mutate_offset;")
    lines.append("    size_t mutate_capacity;")
    lines.append("    size_t len_field1;")
    lines.append("    size_t len_field2;")
    lines.append("    size_t blob_count;")
    lines.append("    const struct cm_native_blob_asset *blobs;")
    lines.append("};")
    lines.append("")

    mode_names: list[str] = []
    for mode_name, spec in MODE_SPECS.items():
        trace = load_trace(spec["trace"])
        base = int(trace["base"], 16)
        mode_names.append(mode_name)
        blob_labels = []
        arg_by_label = {a["label"]: a for a in trace["args"] if a.get("readable")}
        for label, arg_index in spec["args"].items():
            arg = arg_by_label[label]
            blob = bytes.fromhex(arg["head_hex"])
            array_name = f"cm_native_{sanitize_name(mode_name)}_{label}_bytes"
            lines.append(f"static const unsigned char {array_name}[] = {{")
            lines.append(f"    {c_bytes(blob)}")
            lines.append("};")
            lines.append("")
            blob_name = f"cm_native_{sanitize_name(mode_name)}_{label}"
            lines.append(f"static const struct cm_native_blob_asset {blob_name} = {{")
            lines.append(f'    .label = "{label}",')
            lines.append(f"    .arg_index = {arg_index},")
            lines.append(f"    .orig_addr = UINT64_C(0x{int(arg['addr'], 16):x}),")
            lines.append(f"    .size = {len(blob)},")
            lines.append(f"    .data = {array_name},")
            lines.append("};")
            lines.append("")
            blob_labels.append(blob_name)

        lines.append(
            f"static const struct cm_native_blob_asset cm_native_{sanitize_name(mode_name)}_blobs[] = {{"
        )
        for blob_name in blob_labels:
            lines.append(f"    {blob_name},")
        lines.append("};")
        lines.append("")

        regs = ["UINT64_C(0)"] * 6
        reg_order = ["rdi", "rsi", "rdx", "rcx", "r8", "r9"]
        for reg_name, src in spec["scalars"].items():
            idx = reg_order.index(reg_name)
            regs[idx] = f"UINT64_C(0x{parse_u64(trace['regs'][src]):x})"

        mutate = spec["mutate"]
        mutate_kind_map = {
            "region": "CM_MUTATE_REGION",
            "len_region": "CM_MUTATE_RCX_PAYLOAD",
            "two_strings": "CM_MUTATE_TWO_STRINGS",
        }
        mutate_blob_index = list(spec["args"]).index(mutate["blob"])
        lines.append(f"static const struct cm_native_mode_asset cm_native_{sanitize_name(mode_name)} = {{")
        lines.append(f'    .mode = "{mode_name}",')
        lines.append(f"    .orig_base = UINT64_C(0x{base:x}),")
        lines.append(f"    .func_off = UINT64_C(0x{spec['func_off']:x}),")
        lines.append(f"    .regs = {{ {', '.join(regs)} }},")
        lines.append(f"    .mutate_kind = {mutate_kind_map[mutate['kind']]},")
        lines.append(f"    .mutate_blob_index = {mutate_blob_index},")
        lines.append(f"    .mutate_offset = {mutate['offset']},")
        lines.append(f"    .mutate_capacity = {mutate['capacity']},")
        lines.append(f"    .len_field1 = {mutate.get('len_field1', '(size_t)-1')},")
        lines.append(f"    .len_field2 = {mutate.get('len_field2', '(size_t)-1')},")
        lines.append(f"    .blob_count = {len(blob_labels)},")
        lines.append(f"    .blobs = cm_native_{sanitize_name(mode_name)}_blobs,")
        lines.append("};")
        lines.append("")

    lines.append("static const struct cm_native_mode_asset *cm_native_all_modes[] = {")
    for mode_name in mode_names:
        lines.append(f"    &cm_native_{sanitize_name(mode_name)},")
    lines.append("};")
    lines.append("")
    lines.append("#define CM_NATIVE_MODE_COUNT (sizeof(cm_native_all_modes) / sizeof(cm_native_all_modes[0]))")
    lines.append("")
    lines.append("#endif")
    lines.append("")

    out.write_text("\n".join(lines), encoding="ascii")
    print(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
